# Log
%dev.quarkus.log.level=INFO
%prod.quarkus.log.level=ERROR
quarkus.log.category."br.com.gruponeural".level=INFO
quarkus.log.file.enable=true
quarkus.log.file.path=egg-bff.log
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %p %s%e%n

# API
quarkus.application.name=egg-bff
quarkus.http.host=0.0.0.0
quarkus.http.port=9001
quarkus.http.root-path=/gruponeural/egg/bff/

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/documentacao
quarkus.smallrye-openapi.path=/openapi

# Processador Python
quarkus.rest-client."egg-processador".url=http://localhost:9002
quarkus.rest-client."egg-processador".connect-timeout=30000
quarkus.rest-client."egg-processador".read-timeout=120000
