# Runtime VIDEO PADRAO
backend: ultralytics
model_path: models/egg_yolov8n_eggselect.pt
confidence: 0.35
iou: 0.45
imgsz: 416

target_label: egg
reference_image: config/reference-video-padrao.jpg
diff_threshold: 55
match_distance: 140.0
max_missing: 45
normalize: false
api_host: 0.0.0.0
api_port: 9002
